//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpRecordParser.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("08:00:00")]
        public global::System.TimeSpan WorkingTimeBegin {
            get {
                return ((global::System.TimeSpan)(this["WorkingTimeBegin"]));
            }
            set {
                this["WorkingTimeBegin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("21:00:00")]
        public global::System.TimeSpan WorkingTimeEnd {
            get {
                return ((global::System.TimeSpan)(this["WorkingTimeEnd"]));
            }
            set {
                this["WorkingTimeEnd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IgnoreInternalMissedCalls {
            get {
                return ((bool)(this["IgnoreInternalMissedCalls"]));
            }
            set {
                this["IgnoreInternalMissedCalls"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IgnoreNonworkingTimeMissedCalls {
            get {
                return ((bool)(this["IgnoreNonworkingTimeMissedCalls"]));
            }
            set {
                this["IgnoreNonworkingTimeMissedCalls"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CalcRepeatedMissedAsOne {
            get {
                return ((bool)(this["CalcRepeatedMissedAsOne"]));
            }
            set {
                this["CalcRepeatedMissedAsOne"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int CallbackFirstAttemptMax {
            get {
                return ((int)(this["CallbackFirstAttemptMax"]));
            }
            set {
                this["CallbackFirstAttemptMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int CallbackSecondAttemptMax {
            get {
                return ((int)(this["CallbackSecondAttemptMax"]));
            }
            set {
                this["CallbackSecondAttemptMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("35")]
        public int CallbackThirdAttemptMax {
            get {
                return ((int)(this["CallbackThirdAttemptMax"]));
            }
            set {
                this["CallbackThirdAttemptMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public float MissedCallsGoodMax {
            get {
                return ((float)(this["MissedCallsGoodMax"]));
            }
            set {
                this["MissedCallsGoodMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public float MissedCallsBadMin {
            get {
                return ((float)(this["MissedCallsBadMin"]));
            }
            set {
                this["MissedCallsBadMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public float RegulationGoodMax {
            get {
                return ((float)(this["RegulationGoodMax"]));
            }
            set {
                this["RegulationGoodMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public float RegulationBadMin {
            get {
                return ((float)(this["RegulationBadMin"]));
            }
            set {
                this["RegulationBadMin"] = value;
            }
        }
    }
}
